FROM apache/airflow:3.2.0

# Temporarily switch to root to install the Docker CLI
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends docker.io \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Switch back to the standard Airflow user
USER airflow